# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b66255ba9f2cce2dfa350c4e8b5284bd666907c02b47fa9bd99c95b82a101615481ba93fb12fb8c3e8022e0ea76a89c066e8d42077d982e011fb0fab52226a58

test:
  secret_key_base: e35b848a7ba49a5da767cc865ce0190a2dbc0dcd94e530fa11ff966b131d80630cebc55897f0d69cbcefe204516c80e08b1492b43dab3c750a585d497136375c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
